// Code generated by swaggo/swag. DO NOT EDIT
package api_docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "termsOfService": "https://domain.com",
        "contact": {
            "name": "Support",
            "url": "https://domain.com",
            "email": "contact@domain.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/api/health": {
            "get": {
                "description": "health check",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "/api/health",
                "responses": {
                    "200": {
                        "description": "server unix time",
                        "schema": {
                            "$ref": "#/definitions/api.MSG_RESP_HEALTH"
                        }
                    }
                }
            }
        },
        "/api/kv/create": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kv"
                ],
                "summary": "creat key value pair",
                "parameters": [
                    {
                        "description": "creat key value pair",
                        "name": "msg",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.Msg_Req_CreateKv"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "result",
                        "schema": {
                            "$ref": "#/definitions/api.API_META_STATUS"
                        }
                    }
                }
            }
        },
        "/api/kv/delete": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kv"
                ],
                "summary": "delete key value pair",
                "parameters": [
                    {
                        "description": "delete key value pair",
                        "name": "msg",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.Msg_Req_DeleteKv"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "result",
                        "schema": {
                            "$ref": "#/definitions/api.API_META_STATUS"
                        }
                    }
                }
            }
        },
        "/api/kv/query": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kv"
                ],
                "summary": "query key value pair",
                "parameters": [
                    {
                        "description": "query key value pair",
                        "name": "msg",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.Msg_Req_QueryKv"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "result",
                        "schema": {
                            "$ref": "#/definitions/api.Msg_Resp_QueryKv"
                        }
                    }
                }
            }
        },
        "/api/kv/update": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "kv"
                ],
                "summary": "update key value pair",
                "parameters": [
                    {
                        "description": "update key value pair",
                        "name": "msg",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.Msg_Req_UpdateKv"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "result",
                        "schema": {
                            "$ref": "#/definitions/api.API_META_STATUS"
                        }
                    }
                }
            }
        },
        "/api/user/admin/create": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "admin create user",
                "parameters": [
                    {
                        "description": "update",
                        "name": "msg",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.Msg_Req_CreateUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "result",
                        "schema": {
                            "$ref": "#/definitions/api.API_META_STATUS"
                        }
                    }
                }
            }
        },
        "/api/user/admin/query": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "query user",
                "parameters": [
                    {
                        "description": "query user condition",
                        "name": "msg",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.Msg_Req_QueryUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "result",
                        "schema": {
                            "$ref": "#/definitions/api.Msg_Resp_QueryUser"
                        }
                    }
                }
            }
        },
        "/api/user/admin/update": {
            "post": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "admin update user",
                "parameters": [
                    {
                        "description": "update",
                        "name": "msg",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.Msg_Req_UpdateUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "result",
                        "schema": {
                            "$ref": "#/definitions/api.API_META_STATUS"
                        }
                    }
                }
            }
        },
        "/api/user/auth_config": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "get role setting",
                "responses": {
                    "200": {
                        "description": "result",
                        "schema": {
                            "$ref": "#/definitions/api.Msg_Resp_User_Auth_Config"
                        }
                    }
                }
            }
        },
        "/api/user/captcha": {
            "get": {
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "get captcha",
                "responses": {
                    "200": {
                        "description": "result",
                        "schema": {
                            "$ref": "#/definitions/api.Msg_Resp_Captcha"
                        }
                    }
                }
            }
        },
        "/api/user/email_vcode": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "send email VCode",
                "parameters": [
                    {
                        "description": "get email vcode",
                        "name": "msg",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.Msg_Req_EmailVCode"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "result",
                        "schema": {
                            "$ref": "#/definitions/api.API_META_STATUS"
                        }
                    }
                }
            }
        },
        "/api/user/info": {
            "get": {
                "security": [
                    {
                        "ApiKeyAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "get user info",
                "responses": {
                    "200": {
                        "description": "result",
                        "schema": {
                            "$ref": "#/definitions/api.Msg_Resp_UserInfo"
                        }
                    }
                }
            }
        },
        "/api/user/login": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "user login",
                "parameters": [
                    {
                        "description": "user login",
                        "name": "msg",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.Msg_Req_UserLogin"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "result",
                        "schema": {
                            "$ref": "#/definitions/api.Msg_Resp_UserInfo"
                        }
                    }
                }
            }
        },
        "/api/user/register": {
            "post": {
                "description": "user register",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "user register",
                "parameters": [
                    {
                        "description": "new user info",
                        "name": "msg",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.Msg_Req_RegisterUser"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "result",
                        "schema": {
                            "$ref": "#/definitions/api.Msg_Resp_Token"
                        }
                    }
                }
            }
        },
        "/api/user/reset_password": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user"
                ],
                "summary": "user reset password",
                "parameters": [
                    {
                        "description": "user reset password",
                        "name": "msg",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api.Msg_Req_UserResetPassword"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "result",
                        "schema": {
                            "$ref": "#/definitions/api.API_META_STATUS"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.API_META_STATUS": {
            "type": "object",
            "properties": {
                "meta_message": {
                    "type": "string"
                },
                "meta_status": {
                    "type": "integer"
                }
            }
        },
        "api.DBKV": {
            "type": "object",
            "properties": {
                "created_unixtime": {
                    "type": "integer"
                },
                "description": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "key": {
                    "type": "string"
                },
                "update_unixtime": {
                    "type": "integer"
                },
                "value": {
                    "type": "string"
                }
            }
        },
        "api.MSG_RESP_HEALTH": {
            "type": "object",
            "properties": {
                "unixtime": {
                    "type": "integer"
                }
            }
        },
        "api.Msg_Req_CreateKv": {
            "description": "Msg_Req_CreateRule",
            "type": "object",
            "properties": {
                "description": {
                    "description": "required",
                    "type": "string"
                },
                "key": {
                    "description": "required",
                    "type": "string"
                },
                "value": {
                    "description": "required",
                    "type": "string"
                }
            }
        },
        "api.Msg_Req_CreateUser": {
            "description": "Msg_Req_RegisterNodeUser",
            "type": "object",
            "properties": {
                "email": {
                    "description": "required",
                    "type": "string"
                },
                "password": {
                    "description": "required",
                    "type": "string"
                },
                "permissions": {
                    "description": "required",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "roles": {
                    "description": "required",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.Msg_Req_DeleteKv": {
            "description": "Msg_Req_DeleteKv",
            "type": "object",
            "properties": {
                "filter": {
                    "description": "required",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api.Msg_Req_DeleteKv_Filter"
                        }
                    ]
                }
            }
        },
        "api.Msg_Req_DeleteKv_Filter": {
            "description": "Msg_Req_DeleteKv_Filter",
            "type": "object",
            "properties": {
                "keys": {
                    "description": "required",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.Msg_Req_EmailVCode": {
            "type": "object",
            "properties": {
                "captcha": {
                    "description": "required",
                    "type": "string"
                },
                "captcha_id": {
                    "description": "required",
                    "type": "string"
                },
                "email": {
                    "description": "required",
                    "type": "string"
                },
                "vcode_len": {
                    "description": "required",
                    "type": "integer"
                }
            }
        },
        "api.Msg_Req_QueryKv": {
            "description": "Msg_Req_QueryKv",
            "type": "object",
            "properties": {
                "filter": {
                    "description": "required",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api.Msg_Req_QueryKv_Filter"
                        }
                    ]
                }
            }
        },
        "api.Msg_Req_QueryKv_Filter": {
            "description": "Msg_Req_QueryKv_Filter",
            "type": "object",
            "properties": {
                "keys": {
                    "description": "optional",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.Msg_Req_QueryUser": {
            "description": "Msg_Req_QueryNodeUser",
            "type": "object",
            "properties": {
                "filter": {
                    "description": "required",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api.Msg_Req_QueryUser_Filter"
                        }
                    ]
                },
                "limit": {
                    "description": "optional",
                    "type": "integer"
                },
                "offset": {
                    "description": "optional",
                    "type": "integer"
                }
            }
        },
        "api.Msg_Req_QueryUser_Filter": {
            "description": "Msg_Req_QueryNodeUser_Filter",
            "type": "object",
            "properties": {
                "email_pattern": {
                    "description": "optional",
                    "type": "string"
                },
                "forbidden": {
                    "description": "optional",
                    "type": "boolean"
                },
                "id": {
                    "description": "optional",
                    "type": "integer"
                },
                "token": {
                    "description": "optional",
                    "type": "string"
                }
            }
        },
        "api.Msg_Req_RegisterUser": {
            "description": "Msg_Req_RegisterNodeUser",
            "type": "object",
            "properties": {
                "email": {
                    "description": "required",
                    "type": "string"
                },
                "password": {
                    "description": "required",
                    "type": "string"
                },
                "vcode": {
                    "description": "required",
                    "type": "string"
                }
            }
        },
        "api.Msg_Req_UpdateKv": {
            "description": "Msg_Req_UpdateKv",
            "type": "object",
            "properties": {
                "filter": {
                    "description": "required",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api.Msg_Req_UpdateKv_Filter"
                        }
                    ]
                },
                "update": {
                    "description": "required",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api.Msg_Req_UpdateKv_To"
                        }
                    ]
                }
            }
        },
        "api.Msg_Req_UpdateKv_Filter": {
            "description": "Msg_Req_UpdateKv_Filter",
            "type": "object",
            "properties": {
                "key": {
                    "description": "required",
                    "type": "string"
                }
            }
        },
        "api.Msg_Req_UpdateKv_To": {
            "description": "Msg_Req_UpdateKv_To",
            "type": "object",
            "properties": {
                "description": {
                    "description": "required",
                    "type": "string"
                },
                "value": {
                    "description": "required",
                    "type": "string"
                }
            }
        },
        "api.Msg_Req_UpdateUser": {
            "description": "Msg_Req_UpdateUser",
            "type": "object",
            "properties": {
                "filter": {
                    "description": "required",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api.Msg_Req_UpdateUser_Filter"
                        }
                    ]
                },
                "update": {
                    "description": "required",
                    "allOf": [
                        {
                            "$ref": "#/definitions/api.Msg_Req_UpdateUser_To"
                        }
                    ]
                }
            }
        },
        "api.Msg_Req_UpdateUser_Filter": {
            "description": "Msg_Req_UpdateNodeUser_Filter",
            "type": "object",
            "properties": {
                "id": {
                    "description": "required",
                    "type": "array",
                    "items": {
                        "type": "integer"
                    }
                }
            }
        },
        "api.Msg_Req_UpdateUser_To": {
            "description": "Msg_Req_UpdateNodeUser_To",
            "type": "object",
            "properties": {
                "forbidden": {
                    "description": "optional",
                    "type": "boolean"
                },
                "permissions": {
                    "description": "optional",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "roles": {
                    "description": "optional",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.Msg_Req_UserLogin": {
            "description": "Msg_Req_UserLogin",
            "type": "object",
            "properties": {
                "captcha": {
                    "description": "required",
                    "type": "string"
                },
                "captcha_id": {
                    "description": "required",
                    "type": "string"
                },
                "email": {
                    "description": "required",
                    "type": "string"
                },
                "password": {
                    "description": "required",
                    "type": "string"
                }
            }
        },
        "api.Msg_Req_UserResetPassword": {
            "description": "Msg_Req_UserResetPassword",
            "type": "object",
            "properties": {
                "email": {
                    "description": "required",
                    "type": "string"
                },
                "password": {
                    "description": "required",
                    "type": "string"
                },
                "vcode": {
                    "description": "required",
                    "type": "string"
                }
            }
        },
        "api.Msg_Resp_Captcha": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "meta_message": {
                    "type": "string"
                },
                "meta_status": {
                    "type": "integer"
                }
            }
        },
        "api.Msg_Resp_QueryKv": {
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.DBKV"
                    }
                },
                "meta_message": {
                    "type": "string"
                },
                "meta_status": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "api.Msg_Resp_QueryUser": {
            "description": "Msg_Resp_QueryNodeUser",
            "type": "object",
            "properties": {
                "data": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api.User"
                    }
                },
                "meta_message": {
                    "type": "string"
                },
                "meta_status": {
                    "type": "integer"
                },
                "total_count": {
                    "type": "integer"
                }
            }
        },
        "api.Msg_Resp_Token": {
            "description": "Msg_Resp_Token",
            "type": "object",
            "properties": {
                "meta_message": {
                    "type": "string"
                },
                "meta_status": {
                    "type": "integer"
                },
                "token": {
                    "type": "string"
                }
            }
        },
        "api.Msg_Resp_UserInfo": {
            "description": "Msg_Resp_UserInfo",
            "type": "object",
            "properties": {
                "meta_message": {
                    "type": "string"
                },
                "meta_status": {
                    "type": "integer"
                },
                "user": {
                    "$ref": "#/definitions/api.User"
                }
            }
        },
        "api.Msg_Resp_User_Auth_Config": {
            "type": "object",
            "properties": {
                "meta_message": {
                    "type": "string"
                },
                "meta_status": {
                    "type": "integer"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                }
            }
        },
        "api.User": {
            "type": "object",
            "properties": {
                "created_unixtime": {
                    "type": "integer"
                },
                "email": {
                    "type": "string"
                },
                "forbidden": {
                    "type": "boolean"
                },
                "id": {
                    "type": "integer"
                },
                "is_super_token": {
                    "type": "boolean"
                },
                "password": {
                    "type": "string"
                },
                "permissions": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "register_continent_code": {
                    "type": "string"
                },
                "register_country_code": {
                    "type": "string"
                },
                "register_ip": {
                    "type": "string"
                },
                "register_region": {
                    "type": "string"
                },
                "roles": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "token": {
                    "type": "string"
                },
                "update_unixtime": {
                    "type": "integer"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "",
	BasePath:         "",
	Schemes:          []string{"https"},
	Title:            "api example",
	Description:      "api example",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
